CREATE TABLE IF NOT EXISTS genres (
                      genre_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      name varchar NOT NULL
                   );
CREATE TABLE IF NOT EXISTS mpas (
                       mpa_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       name varchar NOT NULL
                    );
CREATE TABLE IF NOT EXISTS films (
                     film_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                     name varchar NOT NULL,
                     description varchar NOT NULL,
                     release_date date,
                     duration integer,
                     mpa_id INTEGER REFERENCES mpas (mpa_id)
                 );
CREATE TABLE IF NOT EXISTS film_genres (
                    genre_id INTEGER REFERENCES genres (genre_id),
                    film_id INTEGER REFERENCES films (film_id),
                    PRIMARY KEY(genre_id, film_id)
                 );
CREATE TABLE IF NOT EXISTS users (
                   user_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                   email varchar NOT NULL,
                   login varchar UNIQUE NOT NULL,
                   name varchar NOT NULL,
                   birthday date
               );
CREATE TABLE IF NOT EXISTS friend_requests (
                 user_id INTEGER REFERENCES users (user_id),
                 friend_user_id INTEGER REFERENCES users (user_id),
                 PRIMARY KEY(user_id, friend_user_id)
             );
CREATE TABLE IF NOT EXISTS likes (
                 user_id INTEGER REFERENCES users (user_id),
                 film_id INTEGER REFERENCES films (film_id),
                 PRIMARY KEY(user_id, film_id)
             );